/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.27).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.dingweibing.user.api;

import com.dingweibing.user.model.Movie;
import io.swagger.annotations.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-06-01T09:20:51.512Z")

@Validated
@Api(value = "favorites", description = "the favorites API")
public interface FavoritesQueryApi {

    Logger log = LoggerFactory.getLogger(FavoritesQueryApi.class);

    @ApiOperation(value = "Return movies that the user has previously marked as favorite.",
            nickname = "listFavorites",
            notes = "",
            response = Movie.class,
            responseContainer = "List",
            authorizations = {
                    @Authorization(value = "basicAuth")
            }, tags = {"favorites",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "successful operation", response = Movie.class),
            @ApiResponse(code = 204, message = "Movie not found")})
    @RequestMapping(value = "/favorites",
            produces = {"application/json"},
            method = RequestMethod.GET)
    public ResponseEntity<List<Movie>> listFavorites();
}
