/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.27).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.dingweibing.user.api;

import io.swagger.annotations.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-06-01T09:20:51.512Z")

@Validated
@Api(value = "favorites", description = "the favorites API")
public interface FavoritesCommandApi {

    Logger log = LoggerFactory.getLogger(FavoritesCommandApi.class);

    @ApiOperation(value = "", nickname = "favoritesMovieIdPost", notes = "", authorizations = {
            @Authorization(value = "basicAuth")
    }, tags = {})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "successful operation"),
            @ApiResponse(code = 400, message = "Invalid ID supplied")})
    @RequestMapping(value = "/favorites/{movieId}",
            method = RequestMethod.POST)
    public ResponseEntity<Void> favoritesMovieIdPost(@ApiParam(value = "ID of movie to return", required = true) @PathVariable("movieId") String movieId);

}
